name: nio4r

on: [push, pull_request]

jobs:
  build:
    name: >-
      ${{matrix.os}}, ${{matrix.ruby}}
    env:
      CI: true
      TESTOPTS: -v

    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, macos-12, windows-2019 ]
        ruby: [ head, 3.1, '3.0', 2.7, 2.4, jruby, truffleruby-head ]
        include:
          - { os: ubuntu-22.04, ruby: head  }
          - { os: ubuntu-22.04, ruby: 3.2   }
          - { os: windows-2022, ruby: ucrt  }
          - { os: windows-2022, ruby: 3.2   }
        exclude:
          - { os: windows-2019, ruby: head  }
          - { os: windows-2019, ruby: jruby }
          - { os: windows-2019, ruby: truffleruby-head }

    steps:
      - name: repo checkout
        uses: actions/checkout@v3

      - name: load ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}

      - name: RubyGems, Bundler Update
        if: |
          !contains('2.4', matrix.ruby)
        run: gem update --system --no-document --conservative

      - name: RubyGems, Bundler Update for Ruby 2.4
        if: |
          contains('2.4', matrix.ruby)
        run: gem update --system 3.3.14 --no-document --conservative

      - name: bundle install
        run: bundle install --path .bundle/gems --without development

      - name: compile
        run: bundle exec rake compile

      - name: test
        run: bundle exec rake spec
        timeout-minutes: 10
